pipeline {
    agent any

    environment {
        KUBECONFIG = 'kubeconfig-credential-id'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch:'master',url:'https://github.com/skykesavanke/Cluster_Creation.git'
            }
        }
        stage('Configuration of kubeconfig file'){
            steps{
                    withCredentials([file(credentialsId: "${kube-config}", variable: 'KUBECONFIG_FILE')]) {
                    script {
                        env.KUBECONFIG = "${env.WORKSPACE}/${KUBECONFIG_FILE}" 
                    }
                    sh 'echo $KUBECONFIG'
                }

            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                     env.KUBECONFIG = 'kubeconfig'
                   
                    bat 'C:\\Users\\kesavank\\kubectl version --client'

                   
                   bat 'kubectl apply -f deployment.yaml'

                  
                    bat 'kubectl apply -f service.yaml'
                }
            }
        }
    }
}
